version: '3.8'

services:
  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    environment:
      KEY: supersecretkey
      ADMIN_EMAIL: it@scratchsolid.co.za
      ADMIN_PASSWORD: admin1234
      DB_CLIENT: sqlite3
      DB_FILENAME: /data/database.db
      WEBSOCKETS_ENABLED: true
    volumes:
      - ./directus-data:/data
    restart: unless-stopped
