-- Export Data from Current Shared Production Database
-- Run: npx wrangler d1 execute scratchsolid-db --remote --file=./scripts/export-current-data.sql

-- This script exports data from the current shared scratchsolid-db
-- The exported data will be imported into the new isolated databases

-- Note: This is a template. Actual table names and export queries need to be
-- adjusted based on the current database schema.

-- Export Portal-specific data
-- SELECT * FROM users WHERE role IN ('admin', 'staff', 'cleaner', 'digital', 'transport');
-- SELECT * FROM cleaner_profiles;
-- SELECT * FROM staff;
-- SELECT * FROM employees;
-- SELECT * FROM leaders;
-- SELECT * FROM roles;
-- SELECT * FROM permissions;
-- SELECT * FROM role_permissions;
-- SELECT * FROM admin_permissions;
-- SELECT * FROM staff_monthly_reviews;
-- SELECT * FROM payroll;
-- SELECT * FROM payroll_adjustments;
-- SELECT * FROM payroll_periods;
-- SELECT * FROM leave_requests;
-- SELECT * FROM leave_balances;
-- SELECT * FROM notifications;
-- SELECT * FROM notification_settings;
-- SELECT * FROM audit_logs;
-- SELECT * FROM activity_logs;
-- SELECT * FROM reports;
-- SELECT * FROM schedules;
-- SELECT * FROM schedule_assignments;
-- SELECT * FROM time_tracking;
-- SELECT * FROM time_off_requests;
-- SELECT * FROM departments;
-- SELECT * FROM teams;
-- SELECT * FROM team_members;
-- SELECT * FROM performance_reviews;
-- SELECT * FROM documents;
-- SELECT * FROM document_versions;
-- SELECT * FROM incident_reports;
-- SELECT * FROM compliance_checks;
-- SELECT * FROM training_records;
-- SELECT * FROM certifications;

-- Export Marketing-specific data
-- SELECT * FROM users WHERE role = 'customer';
-- SELECT * FROM services;
-- SELECT * FROM service_categories;
-- SELECT * FROM service_pricing;
-- SELECT * FROM service_areas;
-- SELECT * FROM loyalty_points;
-- SELECT * FROM referrals;
-- SELECT * FROM referral_rewards;
-- SELECT * FROM promotions;
-- SELECT * FROM promo_codes;
-- SELECT * FROM testimonials;
-- SELECT * FROM reviews;
-- SELECT * FROM faq;
-- SELECT * FROM blog_posts;
-- SELECT * FROM blog_categories;
-- SELECT * FROM contact_submissions;
-- SELECT * FROM newsletters;
-- SELECT * FROM email_templates;
-- SELECT * FROM campaigns;
-- SELECT * FROM campaign_recipients;
-- SELECT * FROM analytics_events;
-- SELECT * FROM page_views;
-- SELECT * FROM quote_requests;
-- SELECT * FROM quotes;
-- SELECT * FROM leaders;
-- SELECT * FROM about_us_content;
-- SELECT * FROM locations;
-- SELECT * FROM quote_logs;
-- SELECT * FROM cleaner_photos;
-- SELECT * FROM client_feedback;
-- SELECT * FROM cleaning_checklist;
-- SELECT * FROM geofences;
-- SELECT * FROM client_preferences;

-- Export Backend-specific data
-- SELECT * FROM booking_services;
-- SELECT * FROM booking_status_history;
-- SELECT * FROM payments;
-- SELECT * FROM payment_methods;
-- SELECT * FROM invoices;
-- SELECT * FROM invoice_items;
-- SELECT * FROM transactions;
-- SELECT * FROM stripe_events;
-- SELECT * FROM stripe_customers;
-- SELECT * FROM webhook_events;
-- SELECT * FROM api_keys;
-- SELECT * FROM api_rate_limits;
-- SELECT * FROM integration_logs;
-- SELECT * FROM system_config;
-- SELECT * EXISTS feature_flags;
