-- Import Data into scratchsolid-portal-db
-- Run: npx wrangler d1 execute scratchsolid-portal-db --remote --file=./scripts/import-portal-data.sql

-- This script imports portal-specific data into the new isolated portal database
-- Run the migrations first: npx wrangler d1 migrations apply scratchsolid-portal-db --remote

-- Note: This is a template. Actual INSERT statements need to be generated
-- from the exported data using the export-current-data.sql script.

-- Import users (staff, admin, cleaner, digital, transport roles)
-- INSERT INTO users (email, password_hash, role, name, phone, address, business_name, business_registration, failed_attempts, locked_until, email_verified, email_verification_token, email_verification_expires, two_factor_enabled, totp_secret, backup_codes, created_at, updated_at)
-- SELECT email, password_hash, role, name, phone, address, business_name, business_registration, failed_attempts, locked_until, email_verified, email_verification_token, email_verification_expires, two_factor_enabled, totp_secret, backup_codes, created_at, updated_at
-- FROM scratchsolid_db_users
-- WHERE role IN ('admin', 'staff', 'cleaner', 'digital', 'transport');

-- Import sessions
-- Import cleaner_profiles
-- Import staff
-- Import employees
-- Import leaders
-- Import roles
-- Import permissions
-- Import role_permissions
-- Import admin_permissions
-- Import staff_monthly_reviews
-- Import payroll
-- Import payroll_adjustments
-- Import payroll_periods
-- Import leave_requests
-- Import leave_balances
-- Import notifications
-- Import notification_settings
-- Import audit_logs
-- Import activity_logs
-- Import reports
-- Import schedules
-- Import schedule_assignments
-- Import time_tracking
-- Import time_off_requests
-- Import departments
-- Import teams
-- Import team_members
-- Import performance_reviews
-- Import documents
-- Import document_versions
-- Import incident_reports
-- Import compliance_checks
-- Import training_records
-- Import certifications
