-- Import Data into scratchsolid-marketing-db
-- Run: npx wrangler d1 execute scratchsolid-marketing-db --remote --file=./scripts/import-marketing-data.sql

-- This script imports marketing-specific data into the new isolated marketing database
-- Run the migrations first: npx wrangler d1 migrations apply scratchsolid-marketing-db --remote

-- Note: This is a template. Actual INSERT statements need to be generated
-- from the exported data using the export-current-data.sql script.

-- Import users (customer role)
-- INSERT INTO users (email, password_hash, role, name, phone, address, business_name, business_registration, failed_attempts, locked_until, email_verified, email_verification_token, email_verification_expires, created_at, updated_at)
-- SELECT email, password_hash, role, name, phone, address, business_name, business_registration, failed_attempts, locked_until, email_verified, email_verification_token, email_verification_expires, created_at, updated_at
-- FROM scratchsolid_db_users
-- WHERE role = 'customer';

-- Import sessions
-- Import password_reset_tokens
-- Import services
-- Import service_categories
-- Import service_pricing
-- Import service_areas
-- Import loyalty_points
-- Import loyalty_transactions
-- Import referrals
-- Import referral_rewards
-- Import promotions
-- Import promo_codes
-- Import promo_distribution
-- Import short_urls
-- Import promo_scans
-- Import testimonials
-- Import reviews
-- Import faq
-- Import blog_posts
-- Import blog_categories
-- Import contact_submissions
-- Import newsletters
-- Import email_templates
-- Import campaigns
-- Import campaign_recipients
-- Import analytics_events
-- Import page_views
-- Import quote_requests
-- Import quotes
-- Import quote_logs
-- Import leaders
-- Import about_us_content
-- Import locations
-- Import cleaner_photos
-- Import client_feedback
-- Import cleaning_checklist
-- Import geofences
-- Import client_preferences
