/**
 * @module pg-d1
 * @description PostgreSQL-backed adapter implementing the Cloudflare D1
 * prepared-statement interface (`prepare().bind().first()/.all()/.run()`).
 *
 * The internal portal uses two logical databases (`scratchsolid_db` and
 * `training_db`), so this adapter supports multiple connection pools keyed by
 * connection string. See `runtime-context.ts` for the binding wiring.
 *
 * SQLite -> Postgres translation handled here:
 *   - `?` positional placeholders            -> `$1, $2, ...`
 *   - `datetime('now')`                      -> ISO-formatted UTC now (TEXT)
 *   - `datetime('now', '+7 days')` etc.      -> now() +/- interval, TEXT
 *   - `CURRENT_TIMESTAMP`                     -> ISO-formatted UTC now (TEXT)
 *   - `INSERT OR IGNORE`                      -> `INSERT ... ON CONFLICT DO NOTHING`
 */

import { Pool } from 'pg';
import type { PoolClient } from 'pg';

const PG_NOW = `to_char((now() at time zone 'utc'), 'YYYY-MM-DD HH24:MI:SS')`;

const pools = new Map<string, Pool>();

function getPool(connectionString: string): Pool {
  let pool = pools.get(connectionString);
  if (!pool) {
    pool = new Pool({
      connectionString,
      max: Number(process.env.PG_POOL_MAX || 10),
      idleTimeoutMillis: 30_000,
      connectionTimeoutMillis: 10_000,
    });
    pool.on('error', (err) => console.error('[pg-d1] idle client error', err));
    pools.set(connectionString, pool);
  }
  return pool;
}

export function translateSql(sql: string): string {
  let out = '';
  let placeholderIndex = 0;
  let i = 0;
  while (i < sql.length) {
    const ch = sql[i];
    if (ch === "'") {
      out += ch;
      i++;
      while (i < sql.length) {
        out += sql[i];
        if (sql[i] === "'") {
          if (sql[i + 1] === "'") {
            out += sql[i + 1];
            i += 2;
            continue;
          }
          i++;
          break;
        }
        i++;
      }
      continue;
    }
    if (ch === '?') {
      placeholderIndex++;
      out += `$${placeholderIndex}`;
      i++;
      continue;
    }
    out += ch;
    i++;
  }

  out = out.replace(
    /datetime\(\s*'now'\s*,\s*'([+-])\s*(\d+)\s+(second|seconds|minute|minutes|hour|hours|day|days|month|months|year|years)'\s*\)/gi,
    (_m, sign: string, amount: string, unit: string) => {
      const op = sign === '-' ? '-' : '+';
      const normalizedUnit = unit.endsWith('s') ? unit : `${unit}s`;
      return `to_char(((now() at time zone 'utc') ${op} interval '${amount} ${normalizedUnit}'), 'YYYY-MM-DD HH24:MI:SS')`;
    }
  );
  // Handle both DEFAULT (datetime('now')) and inline datetime('now')
  out = out.replace(/datetime\(\s*'now'\s*\)/gi, PG_NOW);
  out = out.replace(/CURRENT_TIMESTAMP/gi, PG_NOW);
  // DDL: INTEGER PRIMARY KEY AUTOINCREMENT -> GENERATED BY DEFAULT AS IDENTITY
  out = out.replace(/INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT/gi, 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
  out = out.replace(/\bAUTOINCREMENT\b/gi, '');

  // Handle IF NOT EXISTS for indexes (Postgres-compatible syntax)
  out = out.replace(/CREATE\s+INDEX\s+IF\s+NOT\s+EXISTS\s+/gi, 'CREATE INDEX IF NOT EXISTS ');

  if (/INSERT\s+OR\s+IGNORE/i.test(out)) {
    out = out.replace(/INSERT\s+OR\s+IGNORE\s+INTO/gi, 'INSERT INTO');
    if (/RETURNING/i.test(out)) {
      out = out.replace(/\bRETURNING\b/i, 'ON CONFLICT DO NOTHING RETURNING');
    } else {
      out = `${out.trimEnd().replace(/;?\s*$/, '')} ON CONFLICT DO NOTHING`;
    }
  }

  return out;
}

export interface D1Result<T = Record<string, unknown>> {
  results: T[];
  success: boolean;
  meta: { changes: number; last_row_id: number | null; rows_read: number; rows_written: number; duration: number };
}

class PgBoundStatement {
  constructor(
    private readonly connectionString: string,
    private readonly sql: string,
    private readonly params: unknown[]
  ) {}

  private async query(): Promise<{ rows: any[]; rowCount: number; duration: number }> {
    const started = Date.now();
    const res = await getPool(this.connectionString).query(this.sql, this.params as any[]);
    return { rows: res.rows, rowCount: res.rowCount ?? 0, duration: Date.now() - started };
  }

  async first<T = Record<string, unknown>>(column?: string): Promise<T | null> {
    const { rows } = await this.query();
    if (rows.length === 0) return null;
    const row = rows[0];
    if (column !== undefined) return (row?.[column] ?? null) as T;
    return row as T;
  }

  async all<T = Record<string, unknown>>(): Promise<D1Result<T>> {
    const { rows, rowCount, duration } = await this.query();
    return {
      results: rows as T[],
      success: true,
      meta: { changes: rowCount, last_row_id: null, rows_read: rows.length, rows_written: 0, duration },
    };
  }

  async run<T = Record<string, unknown>>(): Promise<D1Result<T>> {
    const { rows, rowCount, duration } = await this.query();
    const lastRow = rows.length > 0 ? rows[rows.length - 1] : null;
    return {
      results: rows as T[],
      success: true,
      meta: {
        changes: rowCount,
        last_row_id: lastRow && typeof lastRow.id === 'number' ? lastRow.id : null,
        rows_read: 0,
        rows_written: rowCount,
        duration,
      },
    };
  }

  async raw<T = unknown[]>(): Promise<T[]> {
    const { rows } = await this.query();
    return rows.map((r) => Object.values(r)) as T[];
  }
}

class PgPreparedStatement {
  constructor(private readonly connectionString: string, private readonly translatedSql: string) {}

  bind(...params: unknown[]): PgBoundStatement {
    return new PgBoundStatement(this.connectionString, this.translatedSql, params);
  }
  first<T = Record<string, unknown>>(column?: string): Promise<T | null> {
    return new PgBoundStatement(this.connectionString, this.translatedSql, []).first<T>(column);
  }
  all<T = Record<string, unknown>>(): Promise<D1Result<T>> {
    return new PgBoundStatement(this.connectionString, this.translatedSql, []).all<T>();
  }
  run<T = Record<string, unknown>>(): Promise<D1Result<T>> {
    return new PgBoundStatement(this.connectionString, this.translatedSql, []).run<T>();
  }
  raw<T = unknown[]>(): Promise<T[]> {
    return new PgBoundStatement(this.connectionString, this.translatedSql, []).raw<T>();
  }
}

export class PgD1Database {
  constructor(private readonly connectionString: string) {}

  prepare(sql: string): PgPreparedStatement {
    return new PgPreparedStatement(this.connectionString, translateSql(sql));
  }

  async batch<T = Record<string, unknown>>(statements: PgBoundStatement[]): Promise<D1Result<T>[]> {
    const client: PoolClient = await getPool(this.connectionString).connect();
    try {
      await client.query('BEGIN');
      const results: D1Result<T>[] = [];
      for (const stmt of statements) results.push(await stmt.all<T>());
      await client.query('COMMIT');
      return results;
    } catch (e) {
      await client.query('ROLLBACK');
      throw e;
    } finally {
      client.release();
    }
  }

  async exec(sql: string): Promise<{ count: number; duration: number }> {
    const started = Date.now();
    const res = await getPool(this.connectionString).query(translateSql(sql));
    return { count: res.rowCount ?? 0, duration: Date.now() - started };
  }
}

const instances = new Map<string, PgD1Database>();

/** Returns a D1-compatible database for the given connection string env var. */
export function getPgD1(connectionString: string): PgD1Database {
  let db = instances.get(connectionString);
  if (!db) {
    db = new PgD1Database(connectionString);
    instances.set(connectionString, db);
  }
  return db;
}
