name: Deploy to Cloudflare

on:
  push:
    branches: [main]

jobs:
  deploy-marketing:
    runs-on: ubuntu-latest
    name: Deploy Marketing Site
    defaults:
      run:
        working-directory: marketing-site
    env:
      CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: marketing-site/package-lock.json

      - run: npm ci
      - name: Deploy to Cloudflare Workers
        run: npx wrangler deploy --compatibility-date=2023-03-01
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

  deploy-portal:
    runs-on: ubuntu-latest
    name: Deploy Internal Portal
    defaults:
      run:
        working-directory: internal-portal
    env:
      CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: internal-portal/package-lock.json
